# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://andypan.me/"
defaultContentLanguage = "en"

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

# This is lame, try to find a better way for it.
[markup.goldmark.renderer]
  unsafe = true

[services]
  [services.disqus]
    shortname = 'andypan-me'
